package br.com.ppdchat.view;

/**
 * Created by Roland on 9/29/16.
 */

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 *
 * @author Roland
 */
public class ChatView extends javax.swing.JFrame {

    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
    }

    public void setVisible(){
            /* Create and display the form */
        SwingUtilities.invokeLater(() -> setVisible(true));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        consolePanel = new javax.swing.JScrollPane();
        chatConsole = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        textInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        commandMenu = new javax.swing.JMenu();
        miHelp = new javax.swing.JMenuItem();
        miRoomList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miJoin = new javax.swing.JMenuItem();
        miUserList = new javax.swing.JMenuItem();
        miPrivate = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        chatConsole.setColumns(20);
        chatConsole.setLineWrap(true);
        chatConsole.setRows(5);
        consolePanel.setViewportView(chatConsole);

        getContentPane().add(consolePanel, java.awt.BorderLayout.CENTER);

        southPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        southPanel.setLayout(new java.awt.BorderLayout());
        southPanel.add(textInput, java.awt.BorderLayout.CENTER);

        btnSend.setText("Enviar");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        southPanel.add(btnSend, java.awt.BorderLayout.EAST);

        getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

        commandMenu.setText("Comandos");

        miHelp.setText("Ajuda     /help");
        miHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHelpActionPerformed(evt);
            }
        });
        commandMenu.add(miHelp);

        miRoomList.setText("Listar Salas     /roomlist");
        miRoomList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRoomListActionPerformed(evt);
            }
        });
        commandMenu.add(miRoomList);
        commandMenu.add(jSeparator1);

        miJoin.setText("Entrar numa sala     /join");
        miJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJoinActionPerformed(evt);
            }
        });
        commandMenu.add(miJoin);

        miUserList.setText("Listar Usuários     /userlist");
        miUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserListActionPerformed(evt);
            }
        });
        commandMenu.add(miUserList);

        miPrivate.setText("Messagem Privada     /private");
        miPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrivateActionPerformed(evt);
            }
        });
        commandMenu.add(miPrivate);
        commandMenu.add(jSeparator2);

        miQuit.setText("Sair...     /quit");
        miQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuitActionPerformed(evt);
            }
        });
        commandMenu.add(miQuit);

        menuBar.add(commandMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miHelpActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miRoomListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miJoinActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miUserListActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miPrivateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void miQuitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnSend;
    private javax.swing.JTextArea chatConsole;
    private javax.swing.JMenu commandMenu;
    private javax.swing.JScrollPane consolePanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miHelp;
    private javax.swing.JMenuItem miJoin;
    private javax.swing.JMenuItem miPrivate;
    private javax.swing.JMenuItem miQuit;
    private javax.swing.JMenuItem miRoomList;
    private javax.swing.JMenuItem miUserList;
    private javax.swing.JPanel southPanel;
    private javax.swing.JTextField textInput;
    // End of variables declaration
}
