package br.com.ppdchat.view;

import br.com.ppdchat.controller.ChatController;

import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Created by Roland on 10/5/16.
 */

public class UsernameDialogView extends javax.swing.JFrame {

    /**
     * Creates new form NicknameDialogView
     * @param usernameDialogListener
     */
    public UsernameDialogView(ActionListener usernameDialogListener) {
        initComponents();
        btnEnterChat.addActionListener(usernameDialogListener);
        txtNickname.addActionListener(usernameDialogListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbChooseNick = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        btnEnterChat = new javax.swing.JButton();

        //Center in the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.width) / 2));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbChooseNick.setText("Escolha um Nickname:");
        jPanel1.add(lbChooseNick, java.awt.BorderLayout.NORTH);
        jPanel1.add(txtNickname, java.awt.BorderLayout.CENTER);

        btnEnterChat.setText("Entrar");
        jPanel1.add(btnEnterChat, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }

    private javax.swing.JButton btnEnterChat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbChooseNick;
    private javax.swing.JTextField txtNickname;

    public String getUsername() {
        return txtNickname.getText().trim();
    }
}
